/*
This file is part of Ionlib.  Copyright (C) 2016  Tim Sweet

Ionlib is free software : you can redistribute it and / or modify
it under the terms of the GNU General Public License as published by
the Free Software Foundation, either version 3 of the License, or
(at your option) any later version.

Ionlib is distributed in the hope that it will be useful,
but WITHOUT ANY WARRANTY; without even the implied warranty of
MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.See the
GNU General Public License for more details.

You should have received a copy of the GNU General Public License
along with Ionlib.If not, see <http://www.gnu.org/licenses/>.
*/
#ifndef ION_ASCII_H_
#define ION_ASCII_H_
namespace ion
{
	enum ascii
	{
		CHAR_NULL,
		CHAR_SOH,
		CHAR_STX,
		CHAR_ETX,
		CHAR_EOT,
		CHAR_ENQ,
		CHAR_ACK,
		CHAR_BEL,
		CHAR_BACKSPACE,
		CHAR_TAB,
		CHAR_LINE_FEED,
		CHAR_VERTICAL_TAB,
		CHAR_FORM_FEED,
		CHAR_CARRIAGE_RETURN,
		CHAR_SHIFT_OUT,
		CHAR_SHIFT_IN,
		CHAR_DATA_LINK_ESCAPE,
		CHAR_DEVICE_CTRL_1,
		CHAR_DEVICE_CTRL_2,
		CHAR_DEVICE_CTRL_3,
		CHAR_DEVICE_CTRL_4,
		CHAR_NAK,
		CHAR_SYN,
		CHAR_ETB,
		CHAR_CHANCEL,
		CHAR_EM,
		CHAR_SUBSTITUTE,
		CHAR_ESCAPE,
		CHAR_FILE_SEPARATOR,
		CHAR_GROUP_SEPARATOR,
		CHAR_RECORD_SEPARATOR,
		CHAR_UNIT_SEPARATOR,
		CHAR_SPACE,
		CHAR_BANG,
		CHAR_QUOTE,
		CHAR_POUND,
		CHAR_DOLLAR,
		CHAR_PERCENT,
		CHAR_AMPERSAND,
		CHAR_TICK,
		CHAR_LEFT_PAREN,
		CHAR_RIGHT_PAREN,
		CHAR_STAR,
		CHAR_PLUS,
		CHAR_COMMA,
		CHAR_DASH,
		CHAR_DOT,
		CHAR_SLASH,
		CHAR_0,
		CHAR_1,
		CHAR_2,
		CHAR_3,
		CHAR_4,
		CHAR_5,
		CHAR_6,
		CHAR_7,
		CHAR_8,
		CHAR_9,
		CHAR_COLON,
		CHAR_SEMICOLON,
		CHAR_LESS,
		CHAR_EQUAL,
		CHAR_GREATER,
		CHAR_QUESTION,
		CHAR_AT,
		CHAR_A,
		CHAR_B,
		CHAR_C,
		CHAR_D,
		CHAR_E,
		CHAR_F,
		CHAR_G,
		CHAR_H,
		CHAR_I,
		CHAR_J,
		CHAR_K,
		CHAR_L,
		CHAR_M,
		CHAR_N,
		CHAR_O,
		CHAR_P,
		CHAR_Q,
		CHAR_R,
		CHAR_S,
		CHAR_T,
		CHAR_U,
		CHAR_V,
		CHAR_W,
		CHAR_X,
		CHAR_Y,
		CHAR_Z,
		CHAR_LEFT_BRACKET,
		CHAR_BACKSLASH,
		CHAR_RIGHT_BRACKET,
		CHAR_CARET,
		CHAR_UNDERSCORE,
		CHAR_ACCENT,
		CHAR_a,
		CHAR_b,
		CHAR_c,
		CHAR_d,
		CHAR_e,
		CHAR_f,
		CHAR_g,
		CHAR_h,
		CHAR_i,
		CHAR_j,
		CHAR_k,
		CHAR_l,
		CHAR_m,
		CHAR_n,
		CHAR_o,
		CHAR_p,
		CHAR_q,
		CHAR_r,
		CHAR_s,
		CHAR_t,
		CHAR_u,
		CHAR_v,
		CHAR_w,
		CHAR_x,
		CHAR_y,
		CHAR_z,
		CHAR_LEFT_BRACE,
		CHAR_PIPE,
		CHAR_RIGHT_BRACE,
		CHAR_TILDA,
		CHAR_DELETE
	};
};
#endif //ION_ASCII_H_